In [3]:
from sklearn.metrics.pairwise import cosine_similarity, cosine_distances

In [9]:
cosine_similarity([[3,1]],[[6,2]])                      # 1 similarity means they are very very similar

array([[1.]])

In [10]:
cosine_distances([[3,1]],[[6,2]])               # Formula => cosine dist=1- cosine_similarity

array([[1.11022302e-16]])

In [11]:
cosine_similarity([[3,1]],[[3,2]])

array([[0.96476382]])

In [12]:
doc1 = """
iphone sales contributed to 70% of revenue. iphone demand is increasing by 20% yoy. 
the main competitor phone galaxy recorded 5% less growth compared to iphone"
"""

doc2 = """
The upside pressure on volumes for the iPhone 12 series, historical outperformance 
in the July-September time period heading into launch event, and further catalysts in relation
to outperformance for iPhone 13 volumes relative to lowered investor expectations implies a 
very attractive set up for the shares.
"""

doc3 = """
samsung's flagship product galaxy is able to penetrate more into asian markets compared to
iphone. galaxy is redesigned with new look that appeals young demographics. 60% of samsung revenues
are coming from galaxy phone sales
"""

doc4 = """
Samsung Electronics unveils its Galaxy S21 flagship, with modest spec improvements 
and a significantly lower price point. Galaxy S21 price is lower by ~20% (much like the iPhone 12A), 
which highlights Samsung's focus on boosting shipments and regaining market share.
"""


In [17]:
import pandas as pd
df=pd.DataFrame([
        {"iPhone" : 3, "galaxy" : 1},                   #coint the number of iPhone and galaxy words come in that doc 
        {"iPhone" : 2, "galaxy" : 0},
        {"iPhone" : 1, "galaxy" : 3},
        {"iPhone" : 1, "galaxy" : 2},
    ],
        index=[                                 # giving the index to that data
            "doc1",
            "doc2",
            "doc3",
            "doc4",
        ]
)
df

iPhone  galaxy
doc1       3       1
doc2       2       0
doc3       1       3
doc4       1       2

In [19]:
df.loc["doc1":"doc1"]

iPhone  galaxy
doc1       3       1

In [20]:
cosine_similarity(df.loc["doc1":"doc1"],df.loc["doc3":"doc3"])      # ->> calculate the similarity between doc1 and doc2

array([[0.6]])

**Observation: Doc1 and Doc3 are not much similar**

In [21]:
cosine_similarity(df.loc["doc1":"doc1"],df.loc["doc2":"doc2"]) 

array([[0.9486833]])

**Observation: Doc1 and Doc2 are much similar**

In [22]:
cosine_similarity(df.loc["doc3":"doc3"],df.loc["doc4":"doc4"])    #-> Much closer andf closer 

array([[0.98994949]])

In [24]:
cosine_distances(df.loc["doc3":"doc3"],df.loc["doc4":"doc4"])     # -> get cosine dist=1- cosine_similarity

array([[0.01005051]])